
import { IBM_Plex_Mono } from "next/font/google";
import './globals.css'
// Fira_Mono
// DM_Mono
// PT_Mono
// B612_Mono
// Molengo
// Inconsolata
// Fira_Code
// JetBrains_Mono
const inconsolata = IBM_Plex_Mono({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Jayvadhiaya's Terminal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={`${inconsolata.className} text-md md:text-lg `}>
        {children}
      </body>
    </html>
  );
}
